services:
  - type: web
    name: course-query-app
    runtime: python
    buildCommand: |
      python -m pip install --upgrade pip
      pip install -r requirements.txt
      npm install --legacy-peer-deps
      CI=false npm run build
    startCommand: gunicorn server:app --log-level debug
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: GROQ_API_KEY
        sync: false
      - key: MONGO_URI
        sync: false
      - key: PYTHONUNBUFFERED
        value: true 