services:
  - type: web
    name: course-query-app
    runtime: python
    buildCommand: npm install react-scripts && npm install && npm run build && pip install -r requirements.txt
    startCommand: gunicorn server:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.8 