services:
  - type: web
    name: course-query-app
    runtime: python
    buildCommand: npm install --legacy-peer-deps && CI=false npm run build && pip install -r requirements.txt
    startCommand: gunicorn server:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: GROQ_API_KEY
        sync: false
      - key: MONGO_URI
        sync: false 