services:
  - type: web
    name: course-query-app
    runtime: python
    buildCommand: cd $RENDER_PROJECT_DIR && npm ci && npm run build && pip install -r requirements.txt
    startCommand: gunicorn server:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.8 